# Generated by Django 5.2.5 on 2025-09-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('CSM', 'CSM'), ('DIRECTOR', 'Director'), ('EMPLOYEE', 'Employee')], default='CUSTOMER', max_length=50),
        ),
    ]
