# Generated by Django 5.2.5 on 2025-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('pilot_name', models.CharField(max_length=250)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('filed_by', models.CharField(blank=True, max_length=250, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(max_length=50)),
                ('tail_number', models.CharField(blank=True, max_length=50)),
                ('uav_type', models.CharField(blank=True, max_length=150)),
                ('gcs_type', models.CharField(blank=True, max_length=100)),
                ('gcs_number', models.CharField(blank=True, max_length=50)),
                ('uav_weight', models.FloatField(help_text='Weight in kg')),
                ('date_of_occurrence', models.DateField(blank=True)),
                ('time_of_occurrence', models.TimeField(blank=True)),
                ('field_site', models.CharField(blank=True, max_length=250)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('damage_level', models.CharField(blank=True, max_length=50)),
                ('flight_mode', models.CharField(blank=True, max_length=50)),
                ('event_phase', models.CharField(blank=True, max_length=50)),
                ('event_description', models.TextField(blank=True)),
                ('initial_actions_taken', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(max_length=200)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('wind', models.CharField(help_text='Wind condition', max_length=100)),
                ('temperature', models.CharField(help_text='Temperature', max_length=50)),
                ('pressure_qnh', models.CharField(help_text='QNH Pressure', max_length=50)),
                ('turbulence', models.BooleanField(default=False)),
                ('windshear', models.BooleanField(default=False)),
                ('rain', models.BooleanField(default=False)),
                ('icing', models.BooleanField(default=False)),
                ('snow', models.BooleanField(default=False)),
                ('file_video', models.FileField(blank=True, upload_to='attachments/')),
                ('file_image1', models.FileField(blank=True, upload_to='attachments/')),
                ('file_image2', models.FileField(blank=True, upload_to='attachments/')),
                ('file_image3', models.FileField(blank=True, upload_to='attachments/')),
                ('file_log', models.FileField(blank=True, upload_to='log/')),
                ('damage_potential', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20)),
            ],
        ),
    ]
