# Generated by Django 5.2.6 on 2025-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('awaiting-parts', 'Awaiting Parts'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
