# Generated by Django 5.2.5 on 2025-09-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteorology',
            name='clouds',
        ),
        migrations.RemoveField(
            model_name='meteorology',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='meteorology',
            name='visibility',
        ),
    ]
