# Generated by Django 5.2.5 on 2025-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
