# Generated by Django 5.2.5 on 2025-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorology',
            name='visibility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
