# Generated by Django 5.2.5 on 2025-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0002_remove_meteorology_clouds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='model_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_occurrence',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_occurrence',
            field=models.TimeField(blank=True),
        ),
    ]
