# Generated by Django 5.2.6 on 2026-03-13 03:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('service_request_id', models.CharField(blank=True, help_text='Service request ID if applicable', max_length=100, null=True)),
                ('tail_number', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UAVType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartRequestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('oem_actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cost_for_customer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_invoice', models.FileField(upload_to='')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_datetime', models.DateTimeField(blank=True, null=True)),
                ('dispatch_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('dispatch_datetime', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complain_form.items')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='complain_form.sparepartsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=100)),
                ('command_name', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=200)),
                ('number_of_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('preferred_location', models.CharField(choices=[('oem', 'OEM Facility'), ('user_site', 'User Site'), ('other', 'Other')], max_length=20)),
                ('location_description', models.TextField()),
                ('preferred_date', models.DateField()),
                ('oem_proposed_date', models.DateField(blank=True, null=True)),
                ('total_uavs', models.PositiveIntegerField()),
                ('training_type', models.CharField(choices=[('refresher', 'Refresher Training'), ('initial', 'Initial Training'), ('instructor', 'Instructor Training'), ('custom', 'Custom Training')], max_length=20)),
                ('training_description', models.TextField()),
                ('oem_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_request_status', models.CharField(choices=[('pending', 'Training Pending'), ('in progress', 'Training in progress'), ('completed', 'Training Completed')], max_length=250)),
                ('uav_type', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='complain_form.uavtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sparepartsrequest',
            name='uav_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='complain_form.uavtype'),
        ),
        migrations.AddField(
            model_name='items',
            name='uav_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='complain_form.uavtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='uav_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complain_form.uavtype'),
        ),
    ]
