# Generated by Django 5.2.6 on 2026-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0003_items_sparepartsrequest_uavtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequestitems',
            name='bill_invoice',
        ),
        migrations.AddField(
            model_name='items',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('uav_type', 'items_name')},
        ),
    ]
