# Generated by Django 5.2.5 on 2025-09-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0003_meteorology_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteorology',
            name='visibility',
        ),
    ]
