# Generated by Django 5.2.5 on 2025-09-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0003_event_model_number_alter_event_date_of_occurrence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseverityclassification',
            name='incident_severity',
        ),
    ]
