# Generated by Django 5.2.5 on 2025-12-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0003_event_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='model_number',
            new_name='serial_number',
        ),
    ]
