# Generated by Django 5.2.5 on 2025-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0004_remove_meteorology_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseverityclassification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='meteorology',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='damage_potential',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Minor', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='file_image1',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='file_image2',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='file_image3',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='file_log',
            field=models.FileField(blank=True, upload_to='log/'),
        ),
        migrations.AddField(
            model_name='event',
            name='file_video',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='icing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='pressure_qnh',
            field=models.CharField(default=20, help_text='QNH Pressure', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='snow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='temperature',
            field=models.CharField(default=20, help_text='Temperature', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='turbulence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='wind',
            field=models.CharField(default=20, help_text='Wind condition', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='windshear',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='EventSeverityClassification',
        ),
        migrations.DeleteModel(
            name='Meteorology',
        ),
    ]
