# Generated by Django 5.2.5 on 2025-12-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0004_rename_model_number_event_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='file_log',
        ),
    ]
