# Generated by Django 5.2.5 on 2025-09-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0004_remove_eventseverityclassification_incident_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorology',
            name='clouds',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meteorology',
            name='humidity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meteorology',
            name='visibility',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
