# Generated by Django 5.2.5 on 2025-09-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0005_meteorology_clouds_meteorology_humidity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meteorology',
            name='clouds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meteorology',
            name='humidity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meteorology',
            name='visibility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
