# Generated by Django 5.2.5 on 2025-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0005_remove_event_file_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gcs_type',
        ),
        migrations.AddField(
            model_name='event',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='logbook_entry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
    ]
