# Generated by Django 5.2.5 on 2025-12-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0006_remove_event_gcs_type_event_clear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pressure_qnh',
        ),
    ]
