# Generated by Django 5.2.5 on 2025-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0007_remove_event_pressure_qnh'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
