# Generated by Django 5.2.5 on 2025-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0008_event_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
