# Generated by Django 5.2.8 on 2025-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0009_alter_event_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uav_weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
