# Generated by Django 5.2.8 on 2025-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0010_alter_event_uav_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
