# Generated by Django 5.2.6 on 2025-12-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0011_alter_event_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='event',
            name='uav_weight',
        ),
        migrations.RemoveField(
            model_name='event',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='event',
            name='wind',
        ),
    ]
