# Generated by Django 5.2.6 on 2026-01-02 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complain_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_pay', models.BooleanField(default=False)),
                ('approved_pay_later', models.BooleanField(default=False)),
                ('approved_through_gem', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('OEM Site', 'OEM Site'), ('Customer Site', 'Customer Site'), ('Virtual Assistance', 'Virtual Assistance')], default='OEM Site', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PRODUCT RECEIVED', 'Product Received'), ('PRE QA REPORT', 'Pre QA Report'), ('DIAGNOSIS REPORT', 'Diagnosis Report'), ('REPAIR', 'Repair'), ('READY FOR DISPATCH', 'Ready for Dispatch'), ('CTF', 'CTF'), ('CLOSED', 'Closed')], default='IN REVIEW', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_statuses', to='complain_form.event')),
            ],
        ),
    ]
