# Generated by Django 5.2.5 on 2025-10-09 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complain_form', '0004_remove_meteorology_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_PROCESS', 'Under Process'), ('COMPLETED', 'Completed')], default='REVIEW', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_statuses', to='complain_form.event')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pricings', to='complain_form.event')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('MANUFACTURER_SITE', 'Manufacturer Site'), ('CUSTOMER_SITE', 'Customer Site'), ('ONLINE', 'Virtual')], default='MANUFACTURER_SITE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='complain_form.event')),
            ],
        ),
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_costs', to='complain_form.event')),
            ],
        ),
    ]
