# Generated by Django 5.2.5 on 2025-09-10 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csmapproval',
            name='location',
        ),
        migrations.RemoveField(
            model_name='csmapproval',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='csmapproval',
            name='status',
        ),
        migrations.CreateModel(
            name='CSMApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_PROCESS', 'Under Process'), ('COMPLETED', 'Completed')], default='REVIEW', max_length=20)),
                ('location', models.CharField(choices=[('CUSTOMER_SITE', 'Customer Site'), ('ON_SITE', 'On Site'), ('COMPANY_SITE', 'Company Site')], default='COMPANY_SITE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('csm_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='oem.csmapproval')),
            ],
        ),
    ]
