# Generated by Django 5.2.5 on 2025-09-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0004_remove_meteorology_visibility'),
        ('oem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csmapprovalhistory',
            name='csm_approval',
        ),
        migrations.AddField(
            model_name='csmapprovalhistory',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='csm_approvals', to='complain_form.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CSMApproval',
        ),
    ]
