# Generated by Django 5.2.5 on 2025-10-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0002_initial'),
        ('oem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='complain_form.event'),
        ),
    ]
