# Generated by Django 5.2.5 on 2025-10-14 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstatus',
            name='attachments',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintstatus',
            name='status',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('DIAGNOSIS', 'Diagnosis'), ('REPAIR', 'Repair'), ('REJECTED', 'Rejected'), ('READY FOR DISPATCH', 'Ready for Dispatch'), ('CLOSED', 'Closed')], default='REVIEW', max_length=20),
        ),
    ]
