# Generated by Django 5.2.5 on 2025-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='status',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PRODUCT_RECEIVED', 'Product Received'), ('DIAGNOSIS', 'Diagnosis'), ('REPAIR', 'Repair'), ('READY FOR DISPATCH', 'Ready for Dispatch'), ('CLOSED', 'Closed')], default='REVIEW', max_length=20),
        ),
    ]
