# Generated by Django 5.2.5 on 2025-09-10 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0006_event_user_alter_meteorology_clouds_and_more'),
        ('oem', '0002_remove_csmapproval_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAQCReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='qaqc/reports/')),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaqc_reviews', to='complain_form.event')),
                ('assigned_team', models.ForeignKey(limit_choices_to={'department': 'QA_QC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oem.team')),
            ],
        ),
    ]
