# Generated by Django 5.2.5 on 2025-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0002_complaintstatus_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
