# Generated by Django 5.2.6 on 2026-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstatus',
            name='oem_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
