# Generated by Django 5.2.6 on 2026-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0003_complaintstatus_oem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpricing',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Service covered under Warranty'), ('PARTIAL', 'Service covered under Partial Warranty'), ('OUT', 'Service covered out of Warranty')], max_length=10, null=True),
        ),
    ]
