# Generated by Django 5.2.5 on 2025-09-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0003_team_qaqcreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
