# Generated by Django 5.2.5 on 2025-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0003_alter_complaintstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpricing',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
