# Generated by Django 5.2.5 on 2025-09-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0004_remove_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaqcreview',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='qaqcreview',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='qaqcreview',
            name='solution_description',
        ),
        migrations.RemoveField(
            model_name='qaqcreview',
            name='status',
        ),
    ]
