# Generated by Django 5.2.5 on 2025-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0004_repaircost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
