# Generated by Django 5.2.5 on 2025-12-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0004_rename_model_number_event_serial_number'),
        ('oem', '0005_alter_complaintstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_statuses', to='complain_form.event'),
        ),
    ]
