# Generated by Django 5.2.5 on 2025-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0005_remove_qaqcreview_estimated_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaqcreview',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='qaqcreview',
            name='assigned_team',
        ),
        migrations.AddField(
            model_name='qaqcreview',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='qaqc_reviews', to='oem.team'),
        ),
    ]
