# Generated by Django 5.2.5 on 2025-09-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0006_remove_qaqcreview_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csmapprovalhistory',
            name='remarks',
        ),
    ]
