# Generated by Django 5.2.5 on 2025-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0006_alter_customerpricing_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpricing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
