# Generated by Django 5.2.5 on 2025-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0007_remove_csmapprovalhistory_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmapprovalhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
