# Generated by Django 5.2.5 on 2025-10-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0005_remove_eventseverityclassification_event_and_more'),
        ('oem', '0007_customerpricing_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpricing',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pricing', to='complain_form.event'),
        ),
    ]
