# Generated by Django 5.2.5 on 2025-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0008_alter_customerpricing_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('OEM_SITE', 'OEM Site'), ('CUSTOMER_SITE', 'Customer Site'), ('VIRTUAL_ASSISTANCE', 'Virtual Assistance')], default='MANUFACTURER_SITE', max_length=20),
        ),
    ]
