# Generated by Django 5.2.5 on 2025-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0008_alter_complaintstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='status',
            field=models.CharField(choices=[('IN REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PRODUCT_RECEIVED', 'Product Received'), ('DIAGNOSIS REPORT', 'Diagnosis Report'), ('REPAIR', 'Repair'), ('READY FOR DISPATCH', 'Ready for Dispatch'), ('CLOSED', 'Closed')], default='REVIEW', max_length=20),
        ),
    ]
