# Generated by Django 5.2.5 on 2025-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0009_remove_qaqcreview_assigned_team_qaqcreview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaqcreview',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
