# Generated by Django 5.2.5 on 2025-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0010_qaqcreview_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaqcreview',
            name='department',
            field=models.CharField(default='asr', max_length=250),
            preserve_default=False,
        ),
    ]
