# Generated by Django 5.2.5 on 2025-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oem', '0011_alter_complaintstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpricing',
            old_name='approved',
            new_name='approved_pay',
        ),
        migrations.AddField(
            model_name='customerpricing',
            name='approved_pay_later',
            field=models.BooleanField(default=False),
        ),
    ]
