# Generated by Django 5.2.5 on 2025-09-13 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_form', '0006_event_user_alter_meteorology_clouds_and_more'),
        ('oem', '0011_qaqcreview_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QAQCReview',
            new_name='ReviewReport',
        ),
    ]
