# Generated by Django 5.2.6 on 2026-01-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=50, unique=True)),
                ('contract_number', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('army_command', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=250, null=True)),
                ('formation', models.CharField(blank=True, max_length=250, null=True)),
                ('warranty_period', models.IntegerField(default=24, help_text='Warranty in months')),
                ('remarks', models.TextField(blank=True)),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
