# Generated by Django 5.2.5 on 2025-10-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('order_name', models.CharField(max_length=255)),
                ('manufecturing_Date', models.DateField()),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('source_location', models.CharField(blank=True, max_length=255, null=True)),
                ('army_command', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=250, null=True)),
                ('formation', models.CharField(blank=True, max_length=250, null=True)),
                ('warranty_period', models.IntegerField(default=24, help_text='Warranty in months')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
