# Generated by Django 5.2.5 on 2025-12-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='source_location',
            new_name='delivery_location',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_sold',
            new_name='obsolete',
        ),
    ]
