# Generated by Django 5.1.7 on 2025-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
