# Generated by Django 5.1.7 on 2025-09-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_model_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model'),
        ),
    ]
